### PR TITLE
Remove web.xml

### PR DESCRIPTION
**Pull request by patcon**
Seems it's not actually a template, but just a file. And since both the installer and standalone packages already come with a copy most-suited to the needs of that version, it's probably best to let them handle it.

This likely hinges on #9

### CODE REVIEW

**Comment by patcon** [comment]
Just realized this doesn't rely on the #9

**Comment by patcon** [comment]
ready for review

**Comment by mvdkleijn** [comment]
This makes sense, but I'll have to check what the difference is between a standard 6.4.11 web.xml and the one we include. I suspect the HTTPS security constraint was added. I'll get back to this.

**Comment by mvdkleijn** [comment]
merged locally

**Pull request closed without merging**
