### PR TITLE
Update database.rb - nix bad mysql::server include

### PR DESCRIPTION
**Pull request by elijah**
Update database.rb - nix bad mysql::server include

### CODE REVIEW

**Comment by mvdkleijn** [comment]
Removing the includes is enough to get the cookbook functional again with the newer library style versions?

**Comment by elijah** [comment]
It should be pretty close.

We might also need to depend on
depends 'mysql2_chef_gem', '~> 1.0.1'
and make similar modifications to what i did in
https://github.com/elijah/cookbook-huginn/blob/master/recipes/database.rb -
the last place that i had to untangle the mysql cookbook and update to the
new library-provider-cookbook-style.

Taking the includes off should at least let the recipe run a bit further -
i'll try to take another pass later today and see what I can do about
getting the right package installs and the various other mysql ecosystem
gems installed, in another pull request.

--e

**Comment by mvdkleijn** [comment]
Right. We don't use MySQL ourselves so I haven't looked at that part yet.

I hope its not a bother but I've now added a `develop` branch. Could you change the target branch for your PRs (this and the other ones) from `master` to `develop`?

I was sick last week and didn't have time to organize the repo more yet. I want to automate the testing etc as much as possible. (more than it is now)

**Comment by elijah** [comment]
I've merged those three pull requests into a single commit on my end, and
re-diff'ed them against your develop branch.

I don't *want* to use mysql on my end, either, but it sure is handy for
some things.  And while I'm staring at it, I feel obligated to fixxit.

best,

--e

**Pull request closed without merging**
